exergam/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views
app_name = 'exergam'

urlpatterns = [ 
    path('logout', LogoutView.as_view(), name='logout'),
    path('', views.FeedView.as_view(), name='load'),
    path('home', views.HomeView.as_view(), name='home'),
    path('<int:pk>/profile', views.ProfileView.as_view(), name='profile'),
    path('userupdate', views.UserUpdateView.as_view(), name='edit'),
    path('feed', views.FeedView.as_view(), name='feed'),
    path('newentry', views.newentry, name='entry'),
    path('upload', views.add_entries, name='upload'),
    path('leaderboard', views.LeaderboardView.as_view(), name='leaderboard'),
    path('myleaderboard', views.MyLeaderboardView.as_view(), name='myleaderboard'),
    path('<int:follow_id>/follow', views.follow, name='follow'),
    path('location', views.location_option, name='location_option'),
    path('select_location', views.LocationView.as_view(), name='select_location'),
    path('newpost/<int:location_id>', views.newpost, name='new_post'),
    path('post', views.add_post, name='post'),
    path('comment/<int:post_id>', views.comment_on_other, name='comment'),
    path('commentown/<int:post_id>', views.comment_on_own, name='comment_own'),
    path('search', views.search, name='search'),
    path('find', views.SearchView.as_view(), name='find'),
    path('<int:unfollow_id>/unfollow', views.unfollow, name='unfollow')
]

projectb14/urls.py
from django.contrib import admin
from django.urls import path, include
#from django.contrib.auth.views import LogoutView
from django.views.generic.base import TemplateView
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('', TemplateView.as_view(template_name='exergam/index.html')),
    path('admin/', admin.site.urls),
    path('exergam/', include('exergam.urls')), #URL https://projectb14test.herokuapp.com/exergam
    path('accounts/', include('allauth.urls')),

    #path('logout', LogoutView.as_view()),
]

exergam/models.py
#Sources
#https://docs.djangoproject.com/en/3.1/ref/models/fields/
#https://pyphilly.org/know-thy-user-custom-user-models-django-allauth/
#https://learndjango.com/tutorials/django-custom-user-model
#https://docs.djangoproject.com/en/3.1/ref/contrib/auth/
#https://docs.djangoproject.com/en/3.1/topics/auth/customizing/#specifying-custom-user-model
#https://www.youtube.com/watch?v=SFarxlTzVX4&ab_channel=CodingWithMitch
#https://www.geeksforgeeks.org/creating-custom-user-model-using-abstractuser-in-django_restframework/
#https://stackoverflow.com/questions/9800490/django-onetoonefield-in-which-model-should-i-put-it
#https://stackoverflow.com/questions/38117069/django-charfield-suitable-for-a-primary-key
#https://stackoverflow.com/questions/16925129/generate-unique-id-in-django-from-a-model-field
#https://docs.djangoproject.com/en/3.1/topics/db/examples/one_to_one/
#https://stackoverflow.com/questions/18941720/auto-creating-related-objects-on-model-creation-in-django
#https://stackoverflow.com/questions/1652550/can-django-automatically-create-a-related-one-to-one-model
#https://stackoverflow.com/questions/5608001/create-onetoone-instance-on-model-creation
#https://stackoverflow.com/questions/26685065/django-create-instance-of-model-from-another-models-save-method
#https://stackoverflow.com/questions/52196365/django-automatically-create-a-model-instance-when-another-model-instance-is-cr/52196467
#https://docs.djangoproject.com/en/2.1/ref/signals/#django.db.models.signals.post_save
#https://stackoverflow.com/questions/3805958/how-to-delete-a-record-in-django-models
#https://depositphotos.com/113097904/stock-illustration-animal-avatars-flat-vector-icons.html for the animal icons

from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError("Users must have an email address.")

        user = self.model(email=self.normalize_email(email))
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(email,password=password)
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    email = models.EmailField(unique = True, blank = False)
    usernm = models.CharField(
        max_length = 40,
        default = "exergam_user"
        )
    first_nm = models.CharField(
        max_length = 40,
        default = "Exergam"
        )
    last_nm = models.CharField(
        max_length = 40,
        default = "User"
        )
    USERNAME_FIELD = 'email' #Something wrong here
    REQUIRED_FIELDS = []

    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    total_points = models.IntegerField(default = 0)

    rank = models.CharField(
        max_length = 30,
        default = 'Unranked'
    )
    PICTURE_CHOICES = [
        ('../images/default.jpeg', 'Default'),
        ('../images/1.jpg', '1'),
        ('../images/2.jpg', '2'),
        ('../images/3.jpg', '3'),
        ('../images/4.jpg', '4'),
        ('../images/5.jpg', '5'),
        ('../images/6.jpg', '6'),
        ('../images/7.jpg', '7'),
        ('../images/8.jpg', '8'),
        ('../images/9.jpg', '9'),
        ('../images/10.jpg', '10'),
        ('../images/12.jpg', '12'),
        ('../images/13.jpg', '13'),
        ('../images/14.jpg', '14'),
        ('../images/15.jpg', '15'),
        ('../images/16.jpg', '16'),
        ('../images/17.jpg', '17'),
        ('../images/18.jpg', '18'),
        ('../images/19.jpg', '19'),
        ('../images/20.jpg', '20'),
    ]

    picture = models.ImageField(choices=PICTURE_CHOICES, default = "../images/default.jpeg")

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return self.is_superuser

    def unranked(self): 
        return self.rank == 'Unranked' 
    
    def bronze(self): 
        return self.rank == 'Bronze' 
    
    def silver(self): 
        return self.rank == 'Silver' 
    
    def gold(self): 
        return self.rank == 'Gold' 
    
    def platinum(self): 
        return self.rank == 'Platinum' 
    
    def diamond(self): 
        return self.rank == 'Diamond'

class ExerciseEntry(models.Model):
    EXERCISE_CHOICES = [
        ('Basketball', 'Basketball'),
        ('Baseball', 'Baseball'),
        ('Climbing', 'Climbing'),
        ('Football', 'Football'),
        ('Frisbee', 'Frisbee'),
        ('Soccer', 'Soccer'),
        ('Spikeball', 'Spikeball'),
        ('Swimming', 'Swimming'),
        ('Tennis', 'Tennis'),
        ('Track + Field', 'Track + Field'),
        ('Volleyball', 'Volleyball'),
        ('Walking', 'Walking'),
        ('Weightlifting', 'Weightlifting'),
        ('Yoga', 'Yoga'),
        ('Cardio', 'Cardio'), #Broad categories from here down to cover the rest
        ('Strength', 'Strength')
    ]
    exercise_type = models.CharField( 
        max_length = 30, 
        choices = EXERCISE_CHOICES, 
        )
    description = models.CharField(
        max_length = 300,
        )
    exercise_date = models.DateTimeField('Date Exercised')
    exercise_duration = models.IntegerField(
        default = 0
    )
    # many-to-one relationship with User
    usr = models.ForeignKey(User, on_delete = models.CASCADE, null=True) 

class Rewards(models.Model):
    # reward_type is just the type of badge, the only valid types are the exercise types e.g. basketball badge
    reward_type = models.CharField(
        max_length = 30,
    )
    
    # many-to-one relationships to User -> each User has associated badges
    usr = models.ForeignKey(User, on_delete = models.CASCADE, null=True) 

class Post(models.Model):
    text = models.TextField()
    date = models.DateTimeField()
    location = models.TextField(default="")
    usr = models.ForeignKey(User, on_delete = models.CASCADE, null=True)

class Comment(models.Model):
    text = models.TextField()
    date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete = models.CASCADE, null=True)
    assc_post = models.ForeignKey(Post, on_delete = models.CASCADE, null=True) #associated post

class Followings(models.Model):
    usr = models.ForeignKey(User,on_delete = models.CASCADE, related_name="following", null=True)
    following_usr = models.ForeignKey(User, on_delete = models.CASCADE, related_name="followers", null=True)


class Location(models.Model):
    name = models.TextField()
    address = models.TextField()

    def __str__(self):
        return self.name + " (" + self.address + ")"

@receiver(post_save, sender=User)
def create_user_cart(sender, instance, created, **kwargs):
    if created:
        Rewards.objects.create(usr=instance)

exergam/forms.py
from django import forms
from .models import ExerciseEntry, Rewards, User, UserManager, Post, Followings, Comment, Location

class UpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('usernm','first_nm','last_nm')

        widgets = {
            'Username': forms.TextInput(attrs={'class': 'form-control'}),
            'First Name': forms.TextInput(attrs={'class': 'form-control'}),
            'Last Name': forms.TextInput(attrs={'class': 'form-control'}),
        }

exergam/templates/exergam/home.html
<!--home.html formats the first page the user goes to after login-->
{% load static %}

{% load socialaccount %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'exergam/style.css' %}">
    <title>Home</title>
</head>

<body>
    <div class="">
        {% if user.is_authenticated %}
        <nav class="navbar navbar-expand-lg navbar-light sticky-top" style="background-color: #4056a1;box-shadow: 0px 8px 24px rgb(13 13 18 / 10%);">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="container">
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <a class="navbar-brand" style="color: #f13c20" href="{% url 'exergam:feed' %}">exergam</a>
                        <li class="nav-item active">
                            <a class="nav-link text-white" href="{% url 'exergam:feed' %}">Home <span
                                    class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link text-white" href="{% url 'exergam:leaderboard' %}">Leaderboards</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link text-white" href="{% url 'exergam:search' %}">Search</a>
                        </li>
                    </ul>
                </div>
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: #fff;">
                            <img src="../../static/images/login.jpeg" alt="Profile" class="avatar">
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'exergam:profile' user.id %}">My Profile</a></li>
                            <li><a class="dropdown-item" href="{% url 'exergam:edit' %}">Edit Profile</a></li>
                            <div class="dropdown-divider"></div>
                            <li><a class="dropdown-item" href="{% url 'exergam:logout' %}">Log Out</a></li>
                        </ul>
                    </li>

                    <li class="nav-item dropdown mr-1">
                        <a class="nav-link" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img src="../../static/images/add.png" alt="Profile" class="mt-3"
                                style="height: 25px; width: 25px;filter: invert(1);">
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'exergam:location_option' %}">Add Post</a></li>
                            <li><a class="dropdown-item" href="{% url 'exergam:entry' %}">Add Exercise</a></li>
                        </ul>
                        
                    </li>                
                </ul>
            </div>
        </nav>

        <div class="container">
            <div class="">
                <h1 class="text-primary">Rewards</h1>
                {% if user.unranked %}<b class="text-primary">Current Rank:</b>
                <p>{{user.rank}}</p> {% endif %}
                {% if user.bronze %}<b class="text-primary">Current Rank:</b>
                <p style="background-color:#826d09">{{user.rank}}</p> {% endif %}
                {% if user.silver %}<b class="text-primary">Current Rank:</b>
                <p style="background-color:#808080">{{user.rank}}</p> {% endif %}
                {% if user.gold %}<b class="text-primary">Current Rank:</b>
                <p style="background-color:#ffd800; color:black">{{user.rank}}</p> {% endif %}
                {% if user.platinum %}<b class="text-primary">Current Rank:</b>
                <p style="background-color:#f8f9ff; color:black">{{user.rank}}</p> {% endif %}
                {% if user.diamond %}<b class="text-primary">Current Rank:</b>
                <p style="background-color:#7afaff; color:black">{{user.rank}}</p> {% endif %}
                <p>{{user.rewards.reward_type}}</p>
    
                <p>{{user.total_points}} points</p>
                <div class="progress">
                    <div class="progress-bar" id="points" role="progressbar" style="width: 0%" aria-valuenow="0"
                        aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <script>
                    var x = document.getElementById("points");
                    var points_string = {{user.total_points}};
                    var points = parseInt(points_string, 10);
                    var percent = (points / 2190000) * 100;
                    var percent_whole = Math.round(percent);
                    x.style.width = percent_whole + "%";
                </script>
            </div>

            <div class="my-5">
                <h1 class="text-primary">Your Posts</h1>
                {% for post in user.post_set.all %}
                <div class="card rounded container mb-2" style="box-shadow: 0px 8px 24px rgb(13 13 18 / 4%);background-color: #ffffffe5;float: left;min-width: 100%;">
                    <div class="d-flex mt-2">
                        <img src="../../static/images/login.jpeg" alt="Profile" class="avatar"></a>
                        <div class="d-flex flex-column pl-3">
                            <h5 style="margin: 0; margin-top: 4px;">{{user.first_nm}} {{user.last_nm}}</h5>
                            <p class="text-muted">{{post.date}} at {{post.location}}</h5>
                            <p>{{post.text}}</p>
                        </div>
                    </div>
                    <hr style="background-color:white;" />
                    <b class="text-primary"> Comments:</b>
                    {% for comment in post.comment_set.all %}
                    <div class="d-flex">
                        <img src="../../static/images/login.jpeg" alt="Profile" style="vertical-align: middle;
                        width: 40px;
                        height: 40px;
                        border-radius: 50%;
                        margin: 5px"></a>
                        <div class="d-flex flex-column pl-3">
                            <p style="margin: 0; margin-top: 6px; line-height: 80%;">{{user.first_nm}} {{user.last_nm}} on {{comment.date}}</p>
                            <p class="text-muted text-wrap" style="width: 50%;">{{comment.text}}</h5>
                        </div>
                    </div>
                    {% endfor %}
                    <form action="{% url 'exergam:comment_own' post.id %}" method="post" class='form'>
                        <textarea class="form-control" id="comment_text" name="comment_text"
                            placeholder="Write a comment here!" rows="3"></textarea>
                        {% csrf_token %}
                        <p></p>
                        <input class="btn btn-outline-primary" type="submit" value="Comment">
                    </form>
                    {% endfor %}
                </div>
                

                <div class="my-5">
                    <h1 class="text-primary">Exercise History</h1>
                    {% for entry in user.exerciseentry_set.all %}
                    <div class="card rounded container w-50 mb-2" style="box-shadow: 0px 8px 24px rgb(13 13 18 / 4%);background-color: #ffffffe5;float: left;">
                        <div class="d-flex my-2">
                            <img class="avatar" src="../../static/images/login.jpeg" alt="Profile">
                            <div class="d-flex flex-column pl-3">
                                <h5 style="margin: 0; margin-top: 4px;">{{user.first_nm}} {{user.last_nm}}</h5>
                                <p class="text-muted">{{entry.exercise_date}}</p>
                            </div>
                        </div>
                        <p class=""><b class="text-primary">Type:</b> {{entry.exercise_type}}</p>
                        <p class=""><b class="text-primary">Duration:</b> {{entry.exercise_duration}} minutes</p>
                        <p class=""><b class="text-primary">Description:</b> {{entry.description}}</p>
                    </div>
                    {% endfor %}
                </div>
                
            </div>
        </div>

        {% endif %}
    </div>

</body>

</html>

exergam/templates/exergam/leaderboard.html
{% load static %}

{% load socialaccount %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'exergam/style.css' %}">
    <title>Leaderboard</title>
</head>

<body style="background-color:#f7f7fa">
    <div class="">
        {% if user.is_authenticated %}
        <nav class="navbar navbar-expand-lg navbar-light sticky-top"
            style="background-color: #fff;border-bottom: 1px solid rgba(var(--b6a,219,219,219),1)">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="container">
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <a class="navbar-brand" href="{% url 'exergam:feed' %}">
                            <img src="../../static/images/icons/eg_logo.png" alt="exergam" style="height: 50px;"></a>
                    </ul>
                </div>

                <form action="{% url 'exergam:find' %}" method="get" class="form-inline my-2 my-lg-0 col mr-5">
                    {% csrf_token %}
                    <input class="form-control" type="text" placeholder="Search" id="search_user" name="search_user"
                        aria-label="Search">
                    <input type="submit" value="&#x1F50D;" class="btn btn-info my-2 my-sm-0">
                </form>

                <ul class="nav navbar-nav ml-auto d-flex align-items-baseline">
                    <li class="nav-item active mr-1">
                        <a class="nav-link text-white" href="{% url 'exergam:feed' %}"> <img
                                src="../../static/images/icons/home.PNG" alt="" style="height: 30px;filter: invert(1)">
                            <span class="sr-only">(current)</span></a>
                    </li>

                    <li class="nav-item active mr-1">
                        <a class="nav-link text-white" href="{% url 'exergam:leaderboard' %}"><img
                                src="../../static/images/icons/medal.png" alt="" style="height: 30px;"></a>
                    </li>

                    <li class="nav-item dropdown mr-1">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:#000000">
                            <img src="{% static user.picture.url %}" alt="Profile" style="
                            width: 45px;
                            height: 45px;
                            border-radius: 50%;">
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'exergam:profile' user.id %}">My Profile</a></li>
                            <div class="dropdown-divider"></div>
                            <li><a class="dropdown-item" href="{% url 'exergam:logout' %}">Log Out</a></li>
                        </ul>
                    </li>

                    <li class="nav-item dropdown mr-1">
                        <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            <img src="../../static/images/add.png" alt="Profile" style="height: 30px; width: 30px;">
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" data-toggle="modal" data-target="#AddPostModal" href="#"> Add
                                    Post</a></li>
                            <li><a class="dropdown-item" data-toggle="modal" data-target="#AddExerciseModal"
                                    href="#">Add Exercise</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>

        <div class="modal fade" id="AddPostModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
            aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Add Post</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <h3 class="">Add a Location to your Post</h3>
                        <form action="{% url 'exergam:select_location' %}" method="GET" class='form'>
                            {% csrf_token %}
                            <input type="text" class="form-control" placeholder="Where did you go?" name="location" ,
                                id="location">
                            <div class="d-flex mt-3 mx-auto">
                                <a class="btn btn-outline-danger mr-1" href="{% url 'exergam:new_post' 1 %}">Skip</a>
                                <input type="submit" value="Search" class="btn btn-primary">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="AddExerciseModal" tabindex="-1" role="dialog"
            aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Add Exercise</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <div class="modal-body">

                        <form action="{% url 'exergam:upload' %}" method="post" class='form'>
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="text-primary">Exercise Type</label>
                                <select name="exercise_type_dropdown" id="exercise_type_dropdown">
                                    <option value="Basketball">Basketball</option>
                                    <option value="Baseball">Baseball</option>
                                    <option value="Climbing">Climbing</option>
                                    <option value="Football">Football</option>
                                    <option value="Frisbee">Frisbee</option>
                                    <option value="Soccer">Soccer</option>
                                    <option value="Spikeball">Spikeball</option>
                                    <option value="Swimming">Swimming</option>
                                    <option value="Tennis">Tennis</option>
                                    <option value="Track + Field">Track + Field</option>
                                    <option value="Volleyball">Volleyball</option>
                                    <option value="Walking">Walking</option>
                                    <option value="Weightlifting">Weightlifting</option>
                                    <option value="Yoga">Yoga</option>
                                    <option value="Cardio">Cardio</option>
                                    <option value="Strength">Strength</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label class="text-primary">Description</label>
                                <input type="text" class="form-control" placeholder="What did you do?"
                                    name="description" , id="description">
                            </div>
                            <div class="form-group">
                                <label class="text-primary" for="exampleInputPassword1">Date</label>
                                <input type="datetime-local" class="form-control" placeholder="YYYY-MM-DD HH:MM"
                                    id="exercise_date" name="exercise_date">
                            </div>
                            <div class="form-group">
                                <label class="text-primary" for="exampleInputPassword1">Duration in minutes</label>
                                <input type="text" class="form-control"
                                    placeholder="For how long did you perform this activity?" id="exercise_duration"
                                    name="exercise_duration">
                            </div>
                            <div class="mx-auto">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <input class="btn btn-outline-primary"
                                    onclick="return confirm('Are you Sure? You will not be able to delete this exercise.')"
                                    type="submit" value="Upload">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <div>
                <img src="../../static/images/icons/crown.png" class="rounded mx-auto d-block" style="
                vertical-align: middle;
                width: 15%;
                height: auto;
                border-radius: 50%;
            ">
            </div>
            <h1 class="text-primary text-center display-3">Leaderboard</h1>

            <ul class="nav nav-pills mb-3 " id="pills-tab" role="tablist">
                <li class="nav-item ml-auto" role="presentation">
                    <a class="nav-link active" href="#">All</a>
                </li>
                <li class="nav-item mr-auto" role="presentation">
                    <a class="nav-link " href="{% url 'exergam:myleaderboard' %}">Personal</a>
                </li>
            </ul>

            {% if ordered_user_list %}
            <table class="table table-hover table-striped">
                <thead>
                    <tr>
                        <th class="text-center" scope="col">Rank</th>
                        <th class="" scope="col">User</th>
                        <th class="text-center" scope="col">XP</th>
                    </tr>
                </thead>
                <tbody>
                    {% for athlete in ordered_user_list %}
                    <tr>
                        <th class="text-center align-middle" scope="row">{{forloop.counter}}</th>
                        <td>
                            <a href="{% url 'exergam:profile' athlete.id %}" class="text-decoration-none">
                                <div class="d-flex">
                                    <img src="{% static athlete.picture.url %}" alt="Profile" style="vertical-align: middle;
                                                    width: 40px;
                                                    height: 40px;
                                                    border-radius: 50%;
                                                    margin: 5px">
                                    <p class="my-auto text-primary">@{{athlete.usernm}}</p>
                                </div>
                            </a>
                        </td>
                        <td class="align-middle text-center">{{athlete.total_points}} XP</td>
                    </tr>

                    {% endfor %}
                </tbody>
            </table>

            {% endif %}
        </div>

</body>
{% endif %}